trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'itatarov'
  imageRepository: 'ivanttrvgsspringbootdocker'
  containerRegistry: 'itatarov.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build and push stage'
  jobs:
  - job: Build
    displayName: 'Build'
    pool:
      vmImage: $(vmImageName)

    steps:
    - script: |
        chmod +x gradlew
        ./gradlew build
      displayName: 'Build with Gradle'

    - task: Docker@2
      displayName: 'Build and push an image to container registry'
      inputs:
        command: 'buildAndPush'
        repository: '$(imageRepository)'
        dockerfile: '$(dockerfilePath)'
        containerRegistry: '$(dockerRegistryServiceConnection)'
        tags: |
          $(tag)