trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Current directory:"
    pwd

    echo "Files here:"
    ls -la

    echo "Find gradlew:"
    find $(Build.SourcesDirectory) -name gradlew

    echo "Find Dockerfile:"
    find $(Build.SourcesDirectory) -name Dockerfile
  displayName: 'Debug file locations'